language: node_js
node_js:
- '0.12.7'
before_install:
- npm install -g gulp-cli
- npm install -g bower
- npm install -g typings
install:
- npm install
- bower install
script:
- gulp
- gulp test